#!/usr/bin/env python3
"""
Translate using word-level dictionary approach.
Extract unique English words, translate them, then compose Chinese meanings.
"""
import re, json, os

INPUT = 'src/data/vocabulary-data.ts'

# Mini dictionary - most common English words in JLPT vocab
D = {
    'pen':'笔','pencil':'铅笔','book':'书','paper':'纸','desk':'桌子','chair':'椅子',
    'table':'桌子','door':'门','window':'窗户','room':'房间','house':'房子','home':'家',
    'school':'学校','class':'班级','teacher':'老师','student':'学生','friend':'朋友',
    'person':'人','people':'人们','man':'男人','woman':'女人','boy':'男孩','girl':'女孩',
    'child':'孩子','baby':'婴儿','family':'家庭','father':'父亲','mother':'母亲',
    'brother':'兄弟','sister':'姐妹','son':'儿子','daughter':'女儿','grandfather':'祖父',
    'grandmother':'祖母','uncle':'叔叔','aunt':'阿姨','husband':'妻子','wife':'妻子',
    'water':'水','fire':'火','wind':'风','rain':'雨','snow':'雪','cloud':'云',
    'sky':'天空','sun':'太阳','moon':'月亮','star':'星星','light':'光','mountain':'山',
    'river':'河','sea':'海','lake':'湖','forest':'森林','tree':'树','flower':'花',
    'grass':'草','leaf':'叶子','fruit':'水果','apple':'苹果','rice':'米饭','bread':'面包',
    'meat':'肉','fish':'鱼','egg':'鸡蛋','milk':'牛奶','tea':'茶','coffee':'咖啡',
    'wine':'酒','beer':'啤酒','salt':'盐','sugar':'糖','oil':'油','soup':'汤',
    'dog':'狗','cat':'猫','bird':'鸟','horse':'马','cow':'牛','pig':'猪',
    'sheep':'羊','chicken':'鸡','rabbit':'兔子','lion':'狮子','tiger':'老虎',
    'bear':'熊','monkey':'猴子','elephant':'大象','snake':'蛇','insect':'昆虫',
    'car':'汽车','train':'火车','bus':'公交车','bicycle':'自行车','ship':'船',
    'boat':'小船','airplane':'飞机','plane':'飞机','truck':'卡车','taxi':'出租车',
    'ticket':'票','station':'车站','airport':'机场','road':'道路','street':'街道',
    'bridge':'桥','park':'公园','garden':'花园','farm':'农场','factory':'工厂',
    'shop':'商店','store':'商店','market':'市场','bank':'银行','hospital':'医院',
    'hotel':'酒店','restaurant':'餐厅','library':'图书馆','museum':'博物馆',
    'church':'教堂','temple':'寺庙','city':'城市','town':'城镇','village':'村庄',
    'country':'国家','world':'世界','island':'岛','beach':'海滩','desert':'沙漠',
    'clothes':'衣服','shirt':'衬衫','coat':'外套','jacket':'夹克','suit':'西装',
    'dress':'连衣裙','skirt':'裙子','pants':'裤子','shoe':'鞋','hat':'帽子',
    'cap':'帽子','glove':'手套','scarf':'围巾','tie':'领带','belt':'皮带',
    'pocket':'口袋','bag':'包','umbrella':'雨伞','wallet':'钱包','key':'钥匙',
    'watch':'手表','glasses':'眼镜','ring':'戒指','mirror':'镜子','comb':'梳子',
    'phone':'电话','camera':'相机','computer':'电脑','radio':'收音机',
    'television':'电视','video':'视频','film':'电影','movie':'电影','music':'音乐',
    'song':'歌曲','art':'艺术','picture':'图片','photo':'照片','book':'书',
    'magazine':'杂志','newspaper':'报纸','news':'新闻','letter':'信',
    'dictionary':'词典','map':'地图','menu':'菜单','note':'笔记','money':'钱',
    'price':'价格','cost':'费用','tax':'税','bill':'账单','cash':'现金',
    'job':'工作','work':'工作','business':'生意','company':'公司','office':'办公室',
    'meeting':'会议','party':'聚会','game':'游戏','sport':'运动','match':'比赛',
    'ball':'球','prize':'奖品','gift':'礼物','tool':'工具','machine':'机器',
    'wheel':'轮子','rope':'绳子','box':'盒子','bottle':'瓶子','cup':'杯子',
    'glass':'玻璃杯','bowl':'碗','plate':'盘子','spoon':'勺子','fork':'叉子',
    'knife':'刀','clock':'时钟','calendar':'日历','name':'名字','age':'年龄',
    'birthday':'生日','life':'生活','love':'爱','hope':'希望','dream':'梦想',
    'fear':'恐惧','anger':'愤怒','joy':'喜悦','sadness':'悲伤','happiness':'幸福',
    'luck':'运气','success':'成功','failure':'失败','peace':'和平','war':'战争',
    'law':'法律','rule':'规则','police':'警察','medicine':'药','doctor':'医生',
    'nurse':'护士','patient':'病人','disease':'疾病','fever':'发烧','cough':'咳嗽',
    'cold':'感冒','head':'头','face':'脸','eye':'眼睛','ear':'耳朵',
    'nose':'鼻子','mouth':'嘴','tooth':'牙齿','tongue':'舌头','neck':'脖子',
    'shoulder':'肩膀','arm':'手臂','hand':'手','finger':'手指','leg':'腿',
    'foot':'脚','knee':'膝盖','back':'背','chest':'胸','heart':'心',
    'blood':'血','bone':'骨头','skin':'皮肤','hair':'头发',
    'color':'颜色','red':'红','blue':'蓝','green':'绿','yellow':'黄',
    'black':'黑','white':'白','brown':'棕','pink':'粉','orange':'橙',
    'purple':'紫','gray':'灰','gold':'金','silver':'银',
    'number':'数字','one':'一','two':'二','three':'三','four':'四','five':'五',
    'six':'六','seven':'七','eight':'八','nine':'九','ten':'十','hundred':'百',
    'thousand':'千','million':'百万','first':'第一','second':'第二','last':'最后',
    'half':'一半','time':'时间','day':'天','week':'周','month':'月','year':'年',
    'hour':'小时','minute':'分钟','morning':'早上','afternoon':'下午','evening':'傍晚',
    'night':'晚上','today':'今天','yesterday':'昨天','tomorrow':'明天','now':'现在',
    'spring':'春天','summer':'夏天','autumn':'秋天','winter':'冬天',
    'go':'去','come':'来','return':'返回','arrive':'到达','leave':'离开',
    'run':'跑','walk':'走','fly':'飞','swim':'游泳','sit':'坐','stand':'站',
    'sleep':'睡觉','eat':'吃','drink':'喝','cook':'做饭','see':'看','look':'看',
    'hear':'听','listen':'听','smell':'闻','taste':'尝','feel':'感觉',
    'touch':'触摸','hold':'握','catch':'抓住','throw':'扔','push':'推','pull':'拉',
    'open':'打开','close':'关闭','cut':'切','break':'打破','wash':'洗','clean':'清洁',
    'write':'写','read':'读','draw':'画','count':'数','think':'想','know':'知道',
    'understand':'理解','remember':'记住','forget':'忘记','believe':'相信',
    'learn':'学习','study':'学习','teach':'教','try':'尝试','ask':'问',
    'answer':'回答','tell':'告诉','say':'说','speak':'说','talk':'谈话',
    'give':'给','take':'拿','receive':'收到','accept':'接受','refuse':'拒绝',
    'send':'发送','bring':'带来','borrow':'借','buy':'买','sell':'卖','pay':'支付',
    'spend':'花费','make':'制作','create':'创造','build':'建造','destroy':'破坏',
    'repair':'修理','change':'改变','grow':'生长','use':'使用','start':'开始',
    'begin':'开始','stop':'停止','finish':'完成','end':'结束','continue':'继续',
    'wait':'等待','stay':'停留','live':'居住','happen':'发生','become':'变成',
    'appear':'出现','disappear':'消失','like':'喜欢','dislike':'不喜欢','hate':'讨厌',
    'choose':'选择','decide':'决定','want':'想要','need':'需要','agree':'同意',
    'help':'帮助','support':'支持','protect':'保护','attack':'攻击','fight':'战斗',
    'win':'赢','lose':'输','travel':'旅行','visit':'拜访','find':'找到',
    'search':'搜索','meet':'遇见','marry':'结婚','die':'死','kill':'杀死',
    'save':'拯救','bathe':'洗澡','shower':'淋浴','wear':'穿','rest':'休息',
    'good':'好的','bad':'坏的','great':'很好的','nice':'好的','wonderful':'精彩的',
    'excellent':'优秀的','poor':'差的','perfect':'完美的','wrong':'错的',
    'right':'对的','correct':'正确的','true':'真的','false':'假的','real':'真的',
    'big':'大的','small':'小的','large':'大的','huge':'巨大的','long':'长的',
    'short':'短的','tall':'高的','low':'低的','high':'高的','wide':'宽的',
    'narrow':'窄的','thick':'厚的','thin':'薄的','deep':'深的','round':'圆的',
    'new':'新的','old':'旧的','young':'年轻的','modern':'现代的','ancient':'古老的',
    'fresh':'新鲜的','clean':'干净的','dirty':'脏的','beautiful':'美丽的',
    'ugly':'丑陋的','pretty':'漂亮的','cute':'可爱的','happy':'快乐的',
    'sad':'悲伤的','angry':'生气的','calm':'平静的','excited':'兴奋的',
    'bored':'无聊的','tired':'累的','hungry':'饿的','full':'饱的','thirsty':'渴的',
    'sick':'生病的','healthy':'健康的','weak':'弱的','strong':'强壮的',
    'fast':'快的','slow':'慢的','quick':'迅速的','easy':'容易的','difficult':'困难的',
    'hard':'难的','simple':'简单的','complex':'复杂的','hot':'热的','cold':'冷的',
    'warm':'温暖的','cool':'凉爽的','wet':'湿的','dry':'干的','bright':'明亮的',
    'dark':'暗的','heavy':'重的','light':'轻的','soft':'软的','smooth':'光滑的',
    'sharp':'锋利的','sweet':'甜的','sour':'酸的','bitter':'苦的','spicy':'辣的',
    'salty':'咸的','delicious':'美味的','expensive':'贵的','cheap':'便宜的',
    'free':'免费的','rich':'富有的','safe':'安全的','dangerous':'危险的',
    'important':'重要的','necessary':'必要的','possible':'可能的','impossible':'不可能的',
    'common':'常见的','rare':'稀有的','strange':'奇怪的','normal':'正常的',
    'natural':'自然的','same':'相同的','different':'不同的','similar':'相似的',
    'equal':'平等的','fair':'公平的','full':'满的','empty':'空的','busy':'忙的',
    'early':'早的','late':'迟的','ready':'准备好的','public':'公共的',
    'private':'私人的','secret':'秘密的','formal':'正式的','official':'官方的',
    'professional':'专业的','traditional':'传统的','foreign':'外国的','domestic':'国内的',
    'local':'本地的','national':'全国的','international':'国际的','global':'全球的',
    'male':'男性的','female':'女性的','single':'单身的','married':'已婚的',
    'adult':'成人的','very':'非常','quite':'相当','too':'太','really':'真的',
    'maybe':'也许','perhaps':'也许','probably':'大概','certainly':'一定',
    'usually':'通常','often':'经常','sometimes':'有时','never':'从不','always':'总是',
    'again':'再次','still':'仍然','already':'已经','just':'刚才','now':'现在',
    'soon':'很快','immediately':'立即','suddenly':'突然','slowly':'慢慢地',
    'quickly':'快速地','well':'好地','together':'一起','alone':'独自',
    'here':'这里','there':'那里','everywhere':'到处','near':'近的','far':'远的',
    'inside':'里面','outside':'外面','up':'向上','down':'向下','back':'回来',
    'about':'关于','above':'上面','below':'下面','under':'在...下','over':'在...上',
    'between':'之间','through':'穿过','around':'周围','after':'之后','before':'之前',
    'during':'在...期间','without':'没有','with':'和','for':'为了','from':'从',
    'into':'进入','onto':'到...上','out':'出去','off':'离开','against':'反对',
    'among':'之中','along':'沿着','across':'横过','toward':'朝','behind':'后面',
    'beside':'旁边','beyond':'超过','within':'在...内','upon':'在...上',
    'ability':'能力','absent':'缺席','accident':'事故','account':'账户',
    'achieve':'实现','action':'行动','active':'积极的','activity':'活动',
    'actual':'实际的','add':'添加','address':'地址','advance':'前进',
    'advanced':'高级的','advantage':'优势','adventure':'冒险','advice':'建议',
    'affair':'事务','affect':'影响','afraid':'害怕的','agency':'代理',
    'agent':'代理人','agree':'同意','agreement':'协议','ahead':'前面',
    'aim':'目标','airline':'航空公司','alarm':'闹钟','alcohol':'酒精',
    'allow':'允许','almost':'几乎','alone':'独自','along':'沿着',
    'ambition':'野心','amount':'数量','amuse':'娱乐','analyze':'分析',
    'ancient':'古老的','anger':'愤怒','angle':'角度','animal':'动物',
    'announce':'宣布','annual':'年度的','answer':'回答','anxious':'焦虑的',
    'any':'任何','anyone':'任何人','anything':'任何事','anywhere':'任何地方',
    'apart':'分开','apartment':'公寓','apologize':'道歉','appeal':'呼吁',
    'appear':'出现','appearance':'外观','appetite':'食欲','application':'申请',
    'apply':'申请','appoint':'任命','appointment':'预约','appreciate':'感激',
    'approach':'接近','appropriate':'适当的','approve':'批准','approximately':'大约',
    'arch':'拱门','area':'区域','argue':'争论','argument':'论点','arise':'产生',
    'army':'军队','arrange':'安排','arrest':'逮捕','arrival':'到达','arrive':'到达',
    'arrow':'箭','article':'文章','ashamed':'羞耻的','aside':'旁边',
    'aspect':'方面','assemble':'集合','assign':'分配','assist':'协助',
    'assistant':'助手','associate':'关联','assume':'假设','assure':'保证',
    'atmosphere':'气氛','attach':'附上','attempt':'尝试','attend':'出席',
    'attention':'注意','attitude':'态度','attract':'吸引','attractive':'有吸引力的',
    'audience':'观众','author':'作者','authority':'权威','available':'可用的',
    'average':'平均的','avoid':'避免','award':'奖励','aware':'意识到的',
    'awful':'可怕的','background':'背景','bacon':'培根','badge':'徽章',
    'baggage':'行李','bake':'烤','bakery':'面包店','balance':'平衡',
    'balcony':'阳台','ballet':'芭蕾舞','balloon':'气球','bamboo':'竹子',
    'banana':'香蕉','band':'乐队','bank':'银行','bar':'酒吧',
    'barber':'理发师','bare':'赤裸的','bargain':'便宜货','barrier':'障碍',
    'base':'基础','baseball':'棒球','basic':'基本的','basin':'盆',
    'basis':'基础','basket':'篮子','bat':'蝙蝠','bath':'洗澡',
    'bathroom':'浴室','battery':'电池','battle':'战斗','bay':'海湾',
    'beam':'横梁','bean':'豆子','beard':'胡须','beat':'打败',
    'beautiful':'美丽的','beauty':'美丽','because':'因为','become':'变成',
    'bed':'床','bedroom':'卧室','bee':'蜜蜂','beef':'牛肉','beer':'啤酒',
    'before':'之前','beg':'乞求','beginner':'初学者','beginning':'开始',
    'behave':'表现','behavior':'行为','behind':'后面','being':'存在',
    'belief':'信念','believe':'相信','bell':'铃','belong':'属于',
    'beneath':'下面','benefit':'利益','beside':'旁边','best':'最好的',
    'bet':'打赌','better':'更好的','between':'之间','beyond':'超过',
    'billion':'十亿','bind':'绑定','biology':'生物','blade':'刀片',
    'blame':'责备','blank':'空白的','blanket':'毯子','bleed':'流血',
    'bless':'祝福','blind':'盲的','block':'街区','blood':'血',
    'blouse':'衬衫','blow':'吹','board':'板','body':'身体',
    'boil':'煮沸','bold':'大胆的','bomb':'炸弹','bond':'纽带',
    'bone':'骨头','bomb':'炸弹','boot':'靴子','border':'边界',
    'bored':'无聊的','boring':'无聊的','borrow':'借','boss':'老板',
    'both':'两者','bother':'打扰','bottom':'底部','bounce':'弹跳',
    'bow':'鞠躬','brain':'大脑','brake':'刹车','branch':'树枝',
    'brand':'品牌','brave':'勇敢的','bread':'面包','break':'打破',
    'breakfast':'早餐','breast':'胸','breath':'呼吸','breathe':'呼吸',
    'breeze':'微风','brick':'砖','bride':'新娘','bridge':'桥',
    'brief':'简短的','brilliant':'辉煌的','bring':'带来','broad':'宽阔的',
    'broadcast':'广播','brush':'刷子','bubble':'泡沫','bucket':'桶',
    'budget':'预算','build':'建造','building':'建筑物','bulb':'灯泡',
    'bull':'公牛','bullet':'子弹','bundle':'捆','burn':'燃烧',
    'burst':'爆发','bury':'埋葬','bush':'灌木','businessman':'商人',
    'but':'但是','butcher':'屠夫','button':'纽扣','buy':'购买',
    'by':'通过','cabin':'船舱','cable':'电缆','cafe':'咖啡馆',
    'cage':'笼子','cake':'蛋糕','calculate':'计算','calendar':'日历',
    'call':'呼叫','calm':'平静的','camp':'露营','campaign':'运动',
    'campus':'校园','can':'能','canal':'运河','cancel':'取消',
    'cancer':'癌症','candidate':'候选人','candle':'蜡烛','candy':'糖果',
    'cannon':'大炮','canoe':'独木舟','canteen':'食堂','canvas':'帆布',
    'capable':'有能力的','capacity':'容量','capital':'首都','captain':'队长',
    'capture':'捕获','card':'卡片','cardboard':'纸板','care':'关心',
    'career':'职业','careful':'小心的','careless':'粗心的','cargo':'货物',
    'carpet':'地毯','carry':'携带','cart':'手推车','case':'箱子',
    'cassette':'磁带','castle':'城堡','casual':'随意的','cat':'猫',
    'catch':'抓住','category':'类别','cattle':'牛','cause':'原因',
    'caution':'谨慎','cave':'洞穴','ceiling':'天花板','celebrate':'庆祝',
    'cell':'细胞','cellar':'地下室','cent':'分','center':'中心',
    'central':'中央的','century':'世纪','ceremony':'仪式','certain':'确定的',
    'certificate':'证书','chain':'链条','chalk':'粉笔','challenge':'挑战',
    'champion':'冠军','chance':'机会','change':'改变','channel':'频道',
    'chapter':'章节','character':'性格','charge':'收费','charm':'魅力',
    'chart':'图表','chase':'追逐','chat':'聊天','cheap':'便宜的',
    'cheat':'欺骗','check':'检查','cheek':'脸颊','cheer':'欢呼',
    'cheese':'奶酪','chef':'厨师','chemistry':'化学','cherry':'樱桃',
    'chess':'国际象棋','chest':'胸部','chew':'咀嚼','chicken':'鸡',
    'chief':'主要的','childhood':'童年','chin':'下巴','china':'瓷器',
    'chip':'芯片','chocolate':'巧克力','choice':'选择','choose':'选择',
    'chorus':'合唱','Christmas':'圣诞节','cigarette':'香烟','cinema':'电影院',
    'circle':'圆圈','circuit':'电路','citizen':'公民','civil':'公民的',
    'claim':'声称','clap':'拍手','clarify':'澄清','classic':'经典的',
    'classroom':'教室','clay':'黏土','clear':'清晰的','clerk':'职员',
    'clever':'聪明的','click':'点击','client':'客户','cliff':'悬崖',
    'climate':'气候','climb':'攀登','clinic':'诊所','cloth':'布',
    'clothing':'服装','cloud':'云','club':'俱乐部','clue':'线索',
    'coach':'教练','coal':'煤','coast':'海岸','cock':'公鸡',
    'code':'代码','coffee':'咖啡','coin':'硬币','collar':'领子',
    'collect':'收集','college':'大学','colony':'殖民地','combine':'结合',
    'come':'来','comfort':'舒适','comfortable':'舒适的','command':'命令',
    'comment':'评论','commerce':'商业','commercial':'商业的','commit':'犯罪',
    'committee':'委员会','communicate':'交流','communication':'交流',
    'community':'社区','companion':'同伴','company':'公司','compare':'比较',
    'compete':'竞争','complain':'抱怨','complete':'完整的','complicated':'复杂的',
    'compliment':'赞美','compose':'组成','composer':'作曲家',
    'composition':'作文','comprehension':'理解','concept':'概念',
    'concern':'关心','concert':'音乐会','conclude':'总结','concrete':'混凝土',
    'condition':'条件','conduct':'进行','conference':'会议','confidence':'信心',
    'confident':'自信的','confirm':'确认','conflict':'冲突','confuse':'使困惑',
    'congratulate':'祝贺','connect':'连接','conquer':'征服',
    'conscious':'有意识的','consequence':'后果','conservative':'保守的',
    'consider':'考虑','consist':'组成','constant':'恒定的',
    'construct':'建设','construction':'建设','consult':'咨询','consume':'消费',
    'contact':'联系','contain':'包含','container':'容器',
    'contemporary':'当代的','content':'内容','contest':'比赛','context':'上下文',
    'continent':'大陆','continue':'继续','continuous':'持续的',
    'contract':'合同','contrary':'相反的','contrast':'对比',
    'contribute':'贡献','control':'控制','convenient':'方便的',
    'conversation':'对话','convey':'传达','convince':'说服','cool':'凉爽的',
    'cooperate':'合作','copper':'铜','copy':'副本','cord':'绳子',
    'core':'核心','corn':'玉米','corner':'角落','corporation':'公司',
    'cost':'花费','costume':'服装','cottage':'小屋','cotton':'棉花',
    'couch':'沙发','cough':'咳嗽','could':'能','council':'委员会',
    'count':'计数','counter':'柜台','countryside':'乡村','county':'县',
    'couple':'夫妻','courage':'勇气','course':'课程','court':'法庭',
    'cousin':'表亲','cover':'覆盖','cow':'奶牛','crack':'裂缝',
    'craft':'手艺','crash':'坠毁','crazy':'疯狂的','cream':'奶油',
    'create':'创造','creature':'生物','credit':'信用','crew':'船员',
    'crime':'犯罪','criminal':'罪犯','crisis':'危机','critic':'评论家',
    'critical':'批判性的','criticism':'批评','criticize':'批评',
    'crop':'农作物','cross':'穿越','crowd':'人群','crowded':'拥挤的',
    'crown':'王冠','crucial':'关键的','cruel':'残忍的','cry':'哭',
    'cucumber':'黄瓜','cultural':'文化的','culture':'文化','cup':'杯子',
    'cure':'治愈','curious':'好奇的','currency':'货币','current':'当前的',
    'curse':'诅咒','curtain':'窗帘','curve':'曲线','cushion':'垫子',
    'custom':'习俗','customer':'顾客','cut':'切','cute':'可爱的',
    'cycle':'循环','daily':'每日的','damage':'损害','damp':'潮湿的',
    'dance':'跳舞','danger':'危险','dangerous':'危险的','dare':'胆敢',
    'dark':'黑暗的','darkness':'黑暗','data':'数据','date':'日期',
    'dawn':'黎明','day':'天','dead':'死的','deaf':'聋的',
    'deal':'交易','dear':'亲爱的','death':'死亡','debate':'辩论',
    'debt':'债务','decade':'十年','decide':'决定','decision':'决定',
    'declare':'宣布','decline':'下降','decorate':'装饰','decrease':'减少',
    'deep':'深的','deer':'鹿','defeat':'击败','defend':'防御',
    'defense':'防御','definite':'明确的','degree':'程度','delay':'延迟',
    'delicate':'精致的','delicious':'美味的','delight':'高兴',
    'deliver':'递送','demand':'需求','democracy':'民主',
    'demonstrate':'证明','dense':'密集的','dentist':'牙医','deny':'否认',
    'depart':'出发','department':'部门','departure':'出发','depend':'依赖',
    'deposit':'存款','depress':'使沮丧','depth':'深度','describe':'描述',
    'description':'描述','desert':'沙漠','deserve':'应得','design':'设计',
    'designer':'设计师','desire':'渴望','desk':'书桌','desperate':'绝望的',
    'despite':'尽管','dessert':'甜点','destination':'目的地',
    'destroy':'破坏','destruction':'破坏','detail':'细节',
    'detailed':'详细的','detect':'发现','determine':'决定','develop':'发展',
    'development':'发展','device':'设备','devote':'奉献','dialogue':'对话',
    'diamond':'钻石','diary':'日记','dictionary':'词典','die':'死',
    'diet':'饮食','differ':'不同','difference':'差异','different':'不同的',
    'difficult':'困难的','difficulty':'困难','dig':'挖','digital':'数字的',
    'dignity':'尊严','dimension':'维度','dine':'进餐','dinner':'晚餐',
    'direct':'直接的','direction':'方向','director':'导演','dirt':'污垢',
    'dirty':'脏的','disadvantage':'劣势','disagree':'不同意',
    'disappear':'消失','disappoint':'使失望','disaster':'灾难',
    'discipline':'纪律','discover':'发现','discovery':'发现',
    'discuss':'讨论','discussion':'讨论','disease':'疾病','dish':'菜肴',
    'disk':'磁盘','dismiss':'解散','display':'展示','dispute':'争端',
    'distance':'距离','distant':'远的','distinct':'明显的',
    'distinguish':'区分','distribute':'分发','district':'区域',
    'disturb':'打扰','dive':'潜水','divide':'分开','division':'分割',
    'divorce':'离婚','doctor':'医生','document':'文件','dog':'狗',
    'doll':'玩偶','dollar':'美元','dominate':'支配','donkey':'驴',
    'door':'门','dot':'点','double':'双倍的','doubt':'怀疑',
    'down':'向下','download':'下载','downtown':'市中心','dozen':'一打',
    'draft':'草稿','drag':'拖','dragon':'龙','drama':'戏剧',
    'dramatic':'戏剧性的','draw':'画','drawer':'抽屉','drawing':'图画',
    'dream':'梦想','dress':'连衣裙','drift':'漂移','drill':'钻头',
    'drink':'喝','drive':'驾驶','driver':'司机','drop':'掉落',
    'drown':'淹死','drug':'药物','drum':'鼓','drunk':'醉的',
    'dry':'干的','duck':'鸭子','due':'到期的','dull':'钝的',
    'dumb':'哑的','dust':'灰尘','duty':'义务','each':'每个',
    'eager':'渴望的','ear':'耳朵','early':'早的','earn':'赚取',
    'earth':'地球','earthquake':'地震','ease':'减轻','east':'东',
    'eastern':'东方的','easy':'容易的','eat':'吃','echo':'回声',
    'economic':'经济的','economy':'经济','edge':'边缘','edit':'编辑',
    'edition':'版本','editor':'编辑','educate':'教育','education':'教育',
    'effect':'效果','effective':'有效的','efficient':'高效的',
    'effort':'努力','egg':'鸡蛋','eight':'八','either':'任何一个',
    'elastic':'有弹性的','elbow':'肘','elder':'年长者','elect':'选举',
    'election':'选举','electric':'电的','electricity':'电',
    'electronic':'电子的','elegant':'优雅的','element':'元素',
    'elephant':'大象','elevator':'电梯','else':'其他','embassy':'大使馆',
    'embrace':'拥抱','emerge':'出现','emergency':'紧急情况',
    'emotion':'情感','emotional':'情感的','emperor':'皇帝',
    'emphasis':'强调','emphasize':'强调','empire':'帝国','employ':'雇用',
    'employee':'雇员','employer':'雇主','empty':'空的','enable':'使能够',
    'encounter':'遇到','encourage':'鼓励','end':'结束','ending':'结局',
    'endless':'无尽的','enemy':'敌人','energy':'能量','engage':'从事',
    'engine':'引擎','engineer':'工程师','enjoy':'享受',
    'enjoyable':'令人愉快的','enormous':'巨大的','enough':'足够的',
    'ensure':'确保','enter':'进入','enterprise':'企业','entertain':'娱乐',
    'enthusiasm':'热情','entire':'整个的','entrance':'入口',
    'envelope':'信封','environment':'环境','equal':'平等的',
    'equipment':'设备','error':'错误','escape':'逃跑',
    'especially':'特别地','essay':'论文','essential':'必要的',
    'establish':'建立','estate':'房地产','estimate':'估计',
    'Europe':'欧洲','European':'欧洲的','eve':'前夜','even':'甚至',
    'event':'事件','eventually':'最终','ever':'曾经','every':'每个',
    'everybody':'每个人','everyone':'每个人','everything':'一切',
    'everywhere':'到处','evidence':'证据','evident':'明显的',
    'evil':'邪恶的','evolution':'进化','exact':'精确的',
    'exactly':'确切地','examine':'检查','example':'例子',
    'excellent':'优秀的','except':'除...外','exception':'例外',
    'excess':'过量','exchange':'交换','excite':'使兴奋',
    'excited':'兴奋的','exciting':'令人兴奋的','exclude':'排除',
    'excuse':'借口','execute':'执行','exercise':'锻炼','exhaust':'耗尽',
    'exhibit':'展览','exhibition':'展览','exist':'存在',
    'existence':'存在','exit':'出口','expand':'扩展','expect':'期望',
    'expectation':'期望','expense':'费用','expensive':'昂贵的',
    'experience':'经验','experiment':'实验','expert':'专家',
    'explain':'解释','explanation':'解释','explode':'爆炸',
    'exploit':'开发','explore':'探索','explosion':'爆炸','export':'出口',
    'expose':'暴露','express':'表达','expression':'表达','extend':'延伸',
    'extension':'延伸','extensive':'广泛的','extent':'程度','extra':'额外的',
    'extraordinary':'非凡的','extreme':'极端的','extremely':'极其',
    'eye':'眼睛','eyebrow':'眉毛','fable':'寓言','face':'脸',
    'facility':'设施','fact':'事实','factor':'因素','factory':'工厂',
    'fade':'褪色','fail':'失败','failure':'失败','faint':'微弱的',
    'fair':'公平的','faith':'信仰','faithful':'忠实的','fake':'假的',
    'fall':'落下','false':'错误的','fame':'名声','familiar':'熟悉的',
    'family':'家庭','famous':'著名的','fan':'风扇','fancy':'花哨的',
    'fantastic':'极好的','far':'远的','fare':'车费','farm':'农场',
    'farmer':'农民','fashion':'时尚','fashionable':'时髦的',
    'fast':'快的','fat':'胖的','fate':'命运','father':'父亲',
    'fault':'过错','favor':'好意','favorite':'最喜欢的','fear':'恐惧',
    'feast':'盛宴','feather':'羽毛','feature':'特征','fee':'费用',
    'feed':'喂养','feel':'感觉','feeling':'感觉','fellow':'家伙',
    'female':'女性的','fence':'栅栏','festival':'节日','fetch':'取来',
    'fever':'发烧','few':'少数','field':'田野','fierce':'凶猛的',
    'fifteen':'十五','fifty':'五十','fight':'战斗','figure':'数字',
    'file':'文件','fill':'填满','film':'电影','final':'最终的',
    'finance':'财政','financial':'金融的','find':'找到','fine':'好的',
    'finger':'手指','finish':'完成','fire':'火','fireman':'消防员',
    'firm':'坚固的','first':'第一','fish':'鱼','fisherman':'渔夫',
    'fit':'合适的','fix':'修理','flag':'旗帜','flame':'火焰',
    'flash':'闪光','flat':'平的','flavor':'味道','flee':'逃跑',
    'flesh':'肉','flexible':'灵活的','flight':'飞行','float':'漂浮',
    'flood':'洪水','floor':'地板','flour':'面粉','flow':'流动',
    'flower':'花','flu':'流感','fluid':'液体','fly':'飞',
    'focus':'焦点','fog':'雾','fold':'折叠','folk':'民间的',
    'follow':'跟随','following':'以下的','fond':'喜爱的','food':'食物',
    'fool':'傻瓜','foolish':'愚蠢的','foot':'脚','football':'足球',
    'for':'为了','forbid':'禁止','force':'力量','forecast':'预报',
    'forehead':'前额','foreign':'外国的','foreigner':'外国人',
    'forest':'森林','forever':'永远','forget':'忘记','forgive':'原谅',
    'fork':'叉子','form':'形式','formal':'正式的','former':'前者',
    'forth':'向前','fortunate':'幸运的','fortune':'财富','forty':'四十',
    'forward':'向前','found':'建立','foundation':'基础',
    'fountain':'喷泉','fox':'狐狸','fragile':'易碎的','frame':'框架',
    'free':'自由的','freedom':'自由','freeze':'冻结','frequent':'频繁的',
    'frequently':'经常','fresh':'新鲜的','fridge':'冰箱','friend':'朋友',
    'friendly':'友好的','friendship':'友谊','frighten':'使害怕',
    'from':'从','front':'前面','frost':'霜','frown':'皱眉',
    'fruit':'水果','fry':'油炸','fuel':'燃料','fulfill':'实现',
    'full':'满的','fun':'乐趣','function':'功能','fund':'资金',
    'fundamental':'基本的','funeral':'葬礼','funny':'有趣的',
    'fur':'毛皮','furniture':'家具','further':'更远',
    'furthermore':'此外','future':'未来','gain':'获得','game':'游戏',
    'garage':'车库','garbage':'垃圾','garden':'花园','gas':'气体',
    'gasoline':'汽油','gate':'大门','gather':'聚集','gaze':'凝视',
    'gear':'齿轮','gender':'性别','general':'一般的','generally':'通常',
    'generation':'一代','generous':'慷慨的','genius':'天才',
    'gentle':'温柔的','gentleman':'绅士','genuine':'真正的',
    'geography':'地理','gesture':'手势','get':'得到','ghost':'鬼',
    'giant':'巨人','gift':'礼物','girl':'女孩','give':'给',
    'glad':'高兴的','glance':'瞥','glare':'怒视','glass':'玻璃',
    'glasses':'眼镜','global':'全球的','globe':'地球','glory':'荣耀',
    'glove':'手套','glue':'胶水','go':'去','goal':'目标',
    'goat':'山羊','god':'神','gold':'金','golden':'金色的',
    'golf':'高尔夫','good':'好的','goodbye':'再见','goods':'商品',
    'goose':'鹅','govern':'统治','government':'政府','grace':'优雅',
    'grade':'等级','gradually':'逐渐地','graduate':'毕业','grain':'谷物',
    'gram':'克','grammar':'语法','grand':'宏伟的','grandchild':'孙辈',
    'granddaughter':'孙女','grandparent':'祖父母','grandson':'孙子',
    'grant':'授予','grape':'葡萄','grasp':'抓住','grass':'草',
    'grateful':'感激的','grave':'坟墓','gray':'灰色','great':'伟大的',
    'greedy':'贪婪的','green':'绿色','greet':'问候','grief':'悲伤',
    'grin':'咧嘴笑','grocery':'杂货','ground':'地面','group':'组',
    'grow':'生长','growth':'生长','guarantee':'保证','guard':'守卫',
    'guess':'猜测','guest':'客人','guide':'导游','guilt':'罪恶感',
    'guilty':'有罪的','gulf':'海湾','gun':'枪','gym':'体育馆',
    'habit':'习惯','hair':'头发','haircut':'理发','half':'一半',
    'hall':'大厅','halt':'停止','ham':'火腿','hammer':'锤子',
    'hand':'手','handbag':'手提包','handful':'一把',
    'handkerchief':'手帕','handle':'把手','handsome':'英俊的',
    'handwriting':'笔迹','hang':'挂','happen':'发生','happy':'快乐的',
    'harbor':'港口','hard':'硬的','hardly':'几乎不','hardship':'困难',
    'hardware':'硬件','harm':'伤害','harmful':'有害的','harmony':'和谐',
    'harvest':'收获','hat':'帽子','hate':'讨厌','have':'有',
    'he':'他','head':'头','headache':'头痛','headline':'标题',
    'headquarters':'总部','health':'健康','healthy':'健康的','heap':'堆',
    'hear':'听','heart':'心','heat':'热','heating':'供暖',
    'heaven':'天堂','heavy':'重的','height':'高度','helicopter':'直升机',
    'hell':'地狱','hello':'你好','help':'帮助','helpful':'有帮助的',
    'hen':'母鸡','her':'她的','here':'这里','hero':'英雄',
    'hide':'隐藏','high':'高的','highway':'高速公路','hike':'徒步',
    'hill':'小山','hint':'暗示','hip':'臀部','hire':'雇用',
    'his':'他的','historic':'历史性的','history':'历史','hit':'打',
    'hobby':'爱好','hold':'握住','hole':'洞','holiday':'假日',
    'hollow':'空心的','holy':'神圣的','home':'家','homeland':'祖国',
    'homesick':'想家的','hometown':'家乡','homework':'作业',
    'honest':'诚实的','honey':'蜂蜜','honor':'荣誉','hook':'钩子',
    'hope':'希望','horizon':'地平线','horn':'角','horrible':'可怕的',
    'horror':'恐怖','horse':'马','hospital':'医院','host':'主人',
    'hot':'热的','hotel':'酒店','hour':'小时','house':'房子',
    'household':'家庭','housewife':'家庭主妇','housing':'住房',
    'how':'如何','however':'然而','huge':'巨大的','human':'人类',
    'humble':'谦虚的','humor':'幽默','hundred':'百','hunger':'饥饿',
    'hungry':'饿的','hunt':'打猎','hunter':'猎人','hurry':'匆忙',
    'hurt':'受伤','husband':'丈夫','ice':'冰','idea':'想法',
    'ideal':'理想的','identify':'识别','idiom':'成语','idiot':'白痴',
    'if':'如果','ignorant':'无知的','ignore':'忽视','ill':'生病的',
    'illegal':'非法的','illness':'疾病','illustrate':'说明','image':'图像',
    'imagination':'想象力','imagine':'想象','imitate':'模仿',
    'immediate':'立即的','immediately':'立即','immigrant':'移民',
    'impact':'影响','imply':'暗示','import':'进口',
    'importance':'重要性','important':'重要的','impose':'强加',
    'impossible':'不可能的','impress':'给...印象','impression':'印象',
    'impressive':'令人印象深刻的','improve':'改善','improvement':'改善',
    'in':'在...里','inch':'英寸','incident':'事件','include':'包括',
    'including':'包括','income':'收入','increase':'增加',
    'incredible':'难以置信的','indeed':'确实','independent':'独立的',
    'indoor':'室内的','industry':'工业','infant':'婴儿','infect':'感染',
    'inferior':'下级的','infinite':'无限的','inflation':'通货膨胀',
    'influence':'影响','inform':'通知','information':'信息',
    'ingredient':'原料','initial':'最初的','initiative':'主动',
    'injure':'伤害','injury':'伤害','ink':'墨水','inn':'客栈',
    'inner':'内部的','innocent':'无辜的','inquire':'询问',
    'inquiry':'查询','insect':'昆虫','inside':'里面','insist':'坚持',
    'inspect':'检查','inspire':'激励','install':'安装',
    'instance':'例子','instant':'即时的','instead':'代替',
    'instinct':'本能','institute':'机构','instruct':'指示',
    'instruction':'指示','instrument':'器具','insurance':'保险',
    'intellectual':'智力的','intelligence':'智力','intelligent':'聪明的',
    'intend':'打算','intense':'强烈的','intention':'意图',
    'interact':'互动','interest':'兴趣','interesting':'有趣的',
    'interfere':'干涉','intermediate':'中级的','international':'国际的',
    'internet':'互联网','interpret':'解释','interrupt':'打断',
    'interval':'间隔','interview':'面试','into':'进入',
    'introduce':'介绍','introduction':'介绍','invade':'入侵',
    'invasion':'入侵','invent':'发明','invention':'发明','invest':'投资',
    'investigate':'调查','investigation':'调查','invitation':'邀请',
    'invite':'邀请','involve':'涉及','iron':'铁','island':'岛',
    'issue':'问题','it':'它','item':'项目','its':'它的',
    'jacket':'夹克','jail':'监狱','jazz':'爵士乐','jealous':'嫉妒的',
    'jeans':'牛仔裤','jet':'喷气式','jewel':'宝石','jewelry':'珠宝',
    'job':'工作','jog':'慢跑','join':'加入','joint':'共同的',
    'joke':'玩笑','journal':'期刊','journalist':'记者','journey':'旅程',
    'joy':'快乐','judge':'法官','judgment':'判断','juice':'果汁',
    'jump':'跳','jungle':'丛林','junior':'年少的','jury':'陪审团',
    'just':'公正的','justice':'正义','justify':'证明...正当',
    'keen':'敏锐的','keep':'保持','ketchup':'番茄酱','kettle':'水壶',
    'key':'钥匙','keyboard':'键盘','kick':'踢','kid':'小孩',
    'kidney':'肾','kill':'杀死','kilo':'公斤','kilogram':'千克',
    'kilometer':'公里','kind':'善良的','king':'国王','kingdom':'王国',
    'kiss':'亲吻','kitchen':'厨房','kite':'风筝','knee':'膝盖',
    'knife':'刀','knight':'骑士','knock':'敲','knot':'结',
    'know':'知道','knowledge':'知识','lab':'实验室','label':'标签',
    'labor':'劳动','laboratory':'实验室','lack':'缺乏','ladder':'梯子',
    'lady':'女士','lake':'湖','lamb':'羊羔','lamp':'灯',
    'land':'土地','landlord':'房东','landscape':'风景','language':'语言',
    'lantern':'灯笼','large':'大的','late':'迟的','later':'后来',
    'latter':'后者','laugh':'笑','launch':'发射','laundry':'洗衣',
    'lavatory':'洗手间','law':'法律','lawn':'草坪','lawyer':'律师',
    'lay':'放置','layer':'层','lazy':'懒惰的','lead':'引导',
    'leader':'领导者','leadership':'领导力','leaf':'叶子','league':'联盟',
    'lean':'倾斜','learn':'学习','least':'最少的','leather':'皮革',
    'leave':'离开','lecture':'讲座','left':'左边','leg':'腿',
    'legal':'合法的','lemon':'柠檬','lemonade':'柠檬水','lend':'借出',
    'length':'长度','less':'较少的','lesson':'课程','let':'让',
    'letter':'信','level':'水平','liberal':'自由的','library':'图书馆',
    'license':'执照','lick':'舔','lid':'盖子','lie':'躺',
    'life':'生命','lifestyle':'生活方式','lift':'举起','lightning':'闪电',
    'like':'喜欢','likely':'可能的','limit':'限制','limited':'有限的',
    'line':'线','link':'链接','lion':'狮子','lip':'嘴唇',
    'liquid':'液体','list':'列表','listen':'听','literary':'文学的',
    'literature':'文学','litter':'垃圾','little':'小的','live':'居住',
    'lively':'活泼的','living':'活的','load':'装载','loaf':'一条面包',
    'loan':'贷款','local':'本地的','locate':'定位','location':'位置',
    'lock':'锁','log':'原木','logic':'逻辑','logical':'合逻辑的',
    'lonely':'孤独的','long':'长的','look':'看','loose':'松的',
    'lord':'领主','lose':'失去','loss':'损失','lost':'迷路的',
    'lot':'很多','loud':'大声的','loudly':'大声地','love':'爱',
    'lovely':'可爱的','low':'低的','loyal':'忠诚的','luck':'运气',
    'lucky':'幸运的','luggage':'行李','lunch':'午餐','lung':'肺',
    'luxury':'奢侈','machine':'机器','mad':'疯的','magazine':'杂志',
    'magic':'魔法','magnet':'磁铁','mail':'邮件','mailbox':'信箱',
    'main':'主要的','mainly':'主要地','maintain':'维持','major':'主要的',
    'majority':'多数','make':'制作','male':'男性的','mall':'商场',
    'man':'男人','manage':'管理','management':'管理','manager':'经理',
    'manner':'方式','manual':'手动的','manufacture':'制造',
    'manuscript':'手稿','many':'许多','map':'地图','margin':'边缘',
    'mark':'标记','market':'市场','marriage':'婚姻','married':'已婚的',
    'marry':'结婚','marvelous':'极好的','mask':'面具','mass':'大量',
    'massive':'大量的','master':'大师','mat':'垫子','match':'比赛',
    'mate':'伙伴','material':'材料','mathematics':'数学','matter':'事情',
    'mature':'成熟的','maximum':'最大值','maybe':'也许','mayor':'市长',
    'meal':'一餐','mean':'意思是','meaning':'意思',
    'meaningful':'有意义的','means':'手段','meantime':'同时',
    'meanwhile':'同时','measure':'测量','measurement':'测量','meat':'肉',
    'mechanic':'机械师','medical':'医学的','medicine':'药',
    'medium':'中等的','meet':'遇见','meeting':'会议','melt':'融化',
    'member':'成员','membership':'会员资格','memorize':'记忆','memory':'记忆',
    'mend':'修补','mental':'精神的','mention':'提及','menu':'菜单',
    'merchant':'商人','mercy':'仁慈','mere':'仅仅的','merely':'仅仅',
    'merry':'快乐的','mess':'混乱','message':'消息','metal':'金属',
    'method':'方法','microphone':'麦克风','microscope':'显微镜',
    'middle':'中间','midnight':'午夜','might':'可能','mild':'温和的',
    'mile':'英里','military':'军事的','milk':'牛奶','million':'百万',
    'mind':'头脑','mine':'我的','mineral':'矿物','minister':'部长',
    'minor':'次要的','minority':'少数','minute':'分钟','miracle':'奇迹',
    'mirror':'镜子','miserable':'悲惨的','miss':'错过','missing':'失踪的',
    'mission':'使命','mistake':'错误','mistaken':'错误的','mix':'混合',
    'mixture':'混合物','mobile':'移动的','model':'模型',
    'moderate':'适度的','modern':'现代的','modest':'谦虚的',
    'mom':'妈妈','moment':'时刻','money':'钱','monitor':'显示器',
    'monkey':'猴子','month':'月','monthly':'每月的','monument':'纪念碑',
    'mood':'心情','moon':'月亮','moral':'道德的','more':'更多',
    'moreover':'此外','morning':'早上','mosquito':'蚊子','most':'最多',
    'mostly':'主要地','mother':'母亲','motion':'运动','motivate':'激励',
    'motor':'马达','mount':'登上','mountain':'山','mouse':'老鼠',
    'mouth':'嘴','move':'移动','movement':'运动','movie':'电影',
    'much':'很多','mud':'泥','multiple':'多个的','murder':'谋杀',
    'muscle':'肌肉','museum':'博物馆','mushroom':'蘑菇','music':'音乐',
    'musician':'音乐家','must':'必须','mutual':'相互的','mystery':'神秘',
    'mysterious':'神秘的','nail':'钉子','naive':'天真的',
    'naked':'裸体的','name':'名字','narrow':'窄的','nation':'国家',
    'national':'国家的','native':'本地的','natural':'自然的',
    'naturally':'自然地','nature':'自然','naughty':'淘气的',
    'navy':'海军','near':'近的','nearby':'附近的','nearly':'几乎',
    'neat':'整洁的','necessary':'必要的','neck':'脖子',
    'necklace':'项链','need':'需要','needle':'针','negative':'否定的',
    'neglect':'忽视','negotiate':'谈判','neighbor':'邻居',
    'neighborhood':'社区','neither':'两者都不','nephew':'侄子',
    'nerve':'神经','nervous':'紧张的','net':'网','network':'网络',
    'never':'从不','nevertheless':'尽管如此','new':'新的',
    'news':'新闻','newspaper':'报纸','next':'下一个','nice':'好的',
    'niece':'侄女','night':'晚上','nine':'九','nineteen':'十九',
    'ninety':'九十','no':'不','noble':'高贵的','nobody':'没有人',
    'nod':'点头','noise':'噪音','none':'没有一个','noon':'中午',
    'nor':'也不','normal':'正常的','north':'北','northern':'北方的',
    'nose':'鼻子','not':'不','note':'笔记','notebook':'笔记本',
    'nothing':'没有东西','notice':'注意','novel':'小说','now':'现在',
    'nowhere':'无处','nuclear':'核的','number':'数字','nurse':'护士',
    'nut':'坚果','obey':'服从','object':'物体','objection':'反对',
    'objective':'客观的','observation':'观察','observe':'观察',
    'obstacle':'障碍','obtain':'获得','obvious':'明显的',
    'obviously':'明显地','occasion':'场合','occupy':'占领','occur':'发生',
    'ocean':'海洋','odd':'奇怪的','of':'的','off':'离开',
    'offense':'冒犯','offer':'提供','office':'办公室','officer':'官员',
    'official':'官方的','often':'经常','oh':'哦','oil':'油',
    'okay':'好的','old':'旧的','Olympic':'奥林匹克的','omit':'省略',
    'on':'在...上','once':'一次','one':'一','onion':'洋葱',
    'online':'在线的','only':'只有','onto':'到...上','open':'打开',
    'opening':'开口','opera':'歌剧','operate':'操作','operation':'手术',
    'opinion':'观点','opportunity':'机会','oppose':'反对',
    'opposite':'对面的','optimistic':'乐观的','option':'选择',
    'or':'或者','oral':'口头的','orange':'橙子','orchestra':'管弦乐队',
    'order':'命令','ordinary':'普通的','organ':'器官','organic':'有机的',
    'organization':'组织','organize':'组织','origin':'起源',
    'original':'原来的','other':'其他的','otherwise':'否则',
    'ought':'应该','our':'我们的','out':'出去','outcome':'结果',
    'outdoor':'户外的','outer':'外部的','outside':'外面','oven':'烤箱',
    'over':'在...上方','overcoat':'大衣','overcome':'克服',
    'overlook':'忽略','overseas':'海外的','own':'自己的',
    'owner':'所有者','oxygen':'氧气','pace':'步伐','pack':'打包',
    'package':'包裹','page':'页','pain':'疼痛','painful':'痛苦的',
    'paint':'油漆','painting':'画作','pair':'一对','palace':'宫殿',
    'pale':'苍白的','pan':'平底锅','pants':'裤子','paper':'纸',
    'parade':'游行','paragraph':'段落','parcel':'包裹','pardon':'原谅',
    'parent':'父母','park':'公园','parking':'停车','parliament':'议会',
    'part':'部分','participate':'参与','particular':'特定的',
    'particularly':'特别地','partly':'部分地','partner':'伙伴',
    'party':'聚会','pass':'通过','passage':'通道','passenger':'乘客',
    'passion':'热情','passionate':'热情的','passive':'被动的',
    'passport':'护照','password':'密码','past':'过去','path':'小路',
    'patience':'耐心','patient':'病人','pattern':'模式','pause':'暂停',
    'pavement':'人行道','pay':'支付','payment':'支付','pea':'豌豆',
    'peace':'和平','peaceful':'和平的','peach':'桃子','peak':'山峰',
    'peanut':'花生','pear':'梨','pearl':'珍珠','peasant':'农民',
    'pen':'钢笔','pencil':'铅笔','penny':'便士','people':'人们',
    'pepper':'胡椒','per':'每','percent':'百分之','perfect':'完美的',
    'perform':'表演','performance':'表演','perhaps':'也许','period':'时期',
    'permanent':'永久的','permission':'许可','permit':'允许',
    'persist':'坚持','person':'人','personal':'个人的',
    'personality':'个性','perspective':'视角','pet':'宠物','phase':'阶段',
    'phenomenon':'现象','philosophy':'哲学','phone':'电话','photo':'照片',
    'photograph':'照片','phrase':'短语','physical':'身体的',
    'physician':'医生','piano':'钢琴','pick':'捡','picnic':'野餐',
    'picture':'图片','pie':'馅饼','piece':'块','pig':'猪',
    'pigeon':'鸽子','pile':'堆','pill':'药片','pillow':'枕头',
    'pilot':'飞行员','pin':'别针','pine':'松树','pink':'粉色',
    'pipe':'管子','pirate':'海盗','pity':'遗憾','pizza':'披萨',
    'place':'地方','plain':'朴素的','plan':'计划','plane':'飞机',
    'planet':'行星','plant':'植物','plastic':'塑料','plate':'盘子',
    'platform':'站台','play':'玩','player':'选手','playground':'操场',
    'pleasant':'愉快的','please':'请','pleasure':'快乐','plenty':'大量',
    'plot':'情节','plug':'插头','plus':'加','pocket':'口袋',
    'poem':'诗','poet':'诗人','poetry':'诗歌','point':'点',
    'poison':'毒药','poisonous':'有毒的','pole':'杆','police':'警察',
    'policeman':'警察','policy':'政策','polish':'擦亮','polite':'礼貌的',
    'political':'政治的','politics':'政治','pollution':'污染',
    'pond':'池塘','pool':'水池','poor':'贫穷的','pop':'流行',
    'popular':'受欢迎的','population':'人口','pork':'猪肉','port':'港口',
    'porter':'搬运工','portion':'部分','portrait':'肖像','position':'位置',
    'positive':'积极的','possess':'拥有','possession':'拥有',
    'possibility':'可能性','possible':'可能的','possibly':'可能地',
    'post':'邮寄','postcard':'明信片','poster':'海报','postpone':'推迟',
    'pot':'锅','potato':'土豆','potential':'潜在的','pound':'磅',
    'pour':'倒','poverty':'贫穷','powder':'粉末','power':'力量',
    'powerful':'强大的','practical':'实用的','practice':'练习',
    'praise':'赞扬','pray':'祈祷','precious':'珍贵的','precise':'精确的',
    'predict':'预测','prefer':'更喜欢','pregnant':'怀孕的',
    'prejudice':'偏见','preparation':'准备','prepare':'准备',
    'presence':'存在','present':'礼物','presentation':'演示',
    'preserve':'保护','president':'总统','press':'按','pressure':'压力',
    'pretend':'假装','pretty':'漂亮的','prevent':'防止',
    'previous':'以前的','price':'价格','pride':'骄傲','priest':'牧师',
    'primary':'主要的','prime':'主要的','prince':'王子','princess':'公主',
    'principal':'校长','principle':'原则','print':'打印','prior':'优先的',
    'priority':'优先','prison':'监狱','prisoner':'囚犯','private':'私人的',
    'prize':'奖品','probable':'可能的','probably':'可能','problem':'问题',
    'procedure':'程序','process':'过程','produce':'生产',
    'producer':'生产者','product':'产品','production':'生产',
    'profession':'职业','professional':'专业的','professor':'教授',
    'profile':'简介','profit':'利润','program':'节目','progress':'进步',
    'prohibit':'禁止','project':'项目','promise':'承诺','promote':'促进',
    'prompt':'迅速的','proof':'证据','proper':'适当的',
    'properly':'适当地','property':'财产','proposal':'提议',
    'propose':'提议','prospect':'前景','protect':'保护',
    'protection':'保护','protest':'抗议','proud':'骄傲的','prove':'证明',
    'provide':'提供','province':'省','psychology':'心理学','pub':'酒吧',
    'public':'公共的','publish':'出版','pull':'拉','pulse':'脉搏',
    'pump':'泵','punctual':'准时的','punish':'惩罚','punishment':'惩罚',
    'pupil':'学生','pure':'纯净的','purple':'紫色','purpose':'目的',
    'purse':'钱包','push':'推','put':'放','puzzle':'谜题',
    'qualification':'资格','qualify':'使合格','quality':'质量',
    'quantity':'数量','quarrel':'争吵','quarter':'四分之一','queen':'女王',
    'quest':'探索','question':'问题','queue':'排队','quick':'快的',
    'quiet':'安静的','quietly':'安静地','quit':'辞职','quite':'相当',
    'quiz':'测验','quotation':'引用','quote':'引用','race':'比赛',
    'racial':'种族的','rack':'架子','radar':'雷达','radiation':'辐射',
    'radio':'收音机','rag':'破布','rail':'铁轨','railroad':'铁路',
    'railway':'铁路','rain':'雨','rainbow':'彩虹','raincoat':'雨衣',
    'raise':'举起','random':'随机的','range':'范围','rank':'排名',
    'rapid':'快速的','rare':'稀有的','rarely':'很少','rat':'老鼠',
    'rate':'比率','rather':'相当','raw':'生的','ray':'光线',
    'razor':'剃刀','reach':'到达','react':'反应','reaction':'反应',
    'read':'读','reader':'读者','reading':'阅读','ready':'准备好的',
    'real':'真的','reality':'现实','realize':'意识到','really':'真的',
    'reason':'原因','reasonable':'合理的','recall':'回忆',
    'receipt':'收据','receive':'收到','recent':'最近的','recently':'最近',
    'recipe':'食谱','recite':'背诵','recognize':'认出','recommend':'推荐',
    'record':'记录','recover':'恢复','recovery':'恢复','recreate':'娱乐',
    'recycle':'回收','red':'红色','reduce':'减少','reduction':'减少',
    'refer':'参考','reference':'参考','reflect':'反映','reflection':'反射',
    'reform':'改革','refresh':'刷新','refrigerator':'冰箱','refuge':'避难',
    'refugee':'难民','refuse':'拒绝','regard':'认为','region':'地区',
    'register':'登记','regret':'后悔','regular':'规则的','regulate':'管理',
    'regulation':'规定','reject':'拒绝','relate':'关联','relation':'关系',
    'relationship':'关系','relative':'亲戚','relax':'放松','release':'释放',
    'relevant':'相关的','reliable':'可靠的','relief':'救济','relieve':'减轻',
    'religion':'宗教','religious':'宗教的','rely':'依赖','remain':'保持',
    'remark':'评论','remarkable':'显著的','remember':'记得','remind':'提醒',
    'remote':'遥远的','remove':'移除','rent':'租金','repair':'修理',
    'repeat':'重复','repeatedly':'反复地','replace':'替换','reply':'回复',
    'report':'报告','reporter':'记者','represent':'代表',
    'representative':'代表','reputation':'名声','request':'请求',
    'require':'需要','requirement':'要求','rescue':'营救','research':'研究',
    'resemble':'相似','reserve':'预订','resist':'抵抗',
    'resistance':'抵抗','resolve':'解决','resort':'度假地',
    'resource':'资源','respect':'尊重','respond':'回应','response':'回应',
    'responsibility':'责任','responsible':'负责的','rest':'休息',
    'restaurant':'餐厅','restore':'恢复','restrict':'限制','result':'结果',
    'retire':'退休','return':'返回','reveal':'揭示','revenge':'复仇',
    'review':'复习','revolution':'革命','reward':'奖赏','rhythm':'节奏',
    'rib':'肋骨','ribbon':'丝带','rice':'米饭','rich':'富有的',
    'rid':'摆脱','ride':'骑','right':'右边','ring':'戒指',
    'rise':'上升','risk':'风险','rival':'对手','river':'河',
    'road':'路','rob':'抢劫','robber':'强盗','robbery':'抢劫',
    'robot':'机器人','rock':'岩石','rocket':'火箭','role':'角色',
    'roll':'滚动','romantic':'浪漫的','roof':'屋顶','room':'房间',
    'root':'根','rope':'绳子','rose':'玫瑰','rough':'粗糙的',
    'round':'圆的','route':'路线','routine':'日常的','row':'排',
    'royal':'皇家的','rubber':'橡胶','rude':'粗鲁的','rug':'地毯',
    'ruin':'毁灭','rule':'规则','ruler':'统治者','run':'跑',
    'runner':'跑步者','rural':'农村的','rush':'冲','sad':'悲伤的',
    'safe':'安全的','safety':'安全','sail':'航行','sailor':'水手',
    'salad':'沙拉','salary':'薪水','sale':'销售','salt':'盐',
    'same':'相同的','sample':'样品','sand':'沙子','satellite':'卫星',
    'satisfaction':'满意','satisfy':'满足','sauce':'酱汁','saucer':'茶碟',
    'sausage':'香肠','save':'保存','saving':'储蓄','say':'说',
    'scale':'规模','scan':'扫描','scarce':'稀少的','scared':'害怕的',
    'scene':'场景','scenery':'风景','schedule':'日程','scheme':'计划',
    'scholar':'学者','scholarship':'奖学金','school':'学校','science':'科学',
    'scientific':'科学的','scientist':'科学家','scissors':'剪刀',
    'scold':'责骂','scoop':'勺','score':'得分','scratch':'抓',
    'scream':'尖叫','screen':'屏幕','screw':'螺丝','sculpture':'雕塑',
    'sea':'海','seal':'密封','search':'搜索','season':'季节',
    'seat':'座位','second':'第二','secondary':'次要的','secret':'秘密',
    'secretary':'秘书','section':'部分','secure':'安全的','security':'安全',
    'see':'看见','seed':'种子','seek':'寻找','seem':'似乎',
    'seize':'抓住','seldom':'很少','select':'选择','self':'自己',
    'sell':'卖','send':'发送','senior':'高级的','sense':'感觉',
    'sensitive':'敏感的','sentence':'句子','separate':'分开的',
    'series':'系列','serious':'严肃的','servant':'仆人','serve':'服务',
    'service':'服务','session':'会议','set':'设置','settle':'解决',
    'settlement':'解决','seven':'七','severe':'严重的','sew':'缝',
    'shadow':'影子','shake':'摇','shall':'将','shame':'羞耻',
    'shape':'形状','share':'分享','shark':'鲨鱼','sharp':'锋利的',
    'shave':'刮胡子','she':'她','sheep':'羊','sheet':'床单',
    'shelf':'架子','shell':'壳','shelter':'庇护','shine':'照耀',
    'ship':'船','shirt':'衬衫','shock':'震惊','shoe':'鞋',
    'shoot':'射击','shop':'商店','shopping':'购物','shore':'海岸',
    'short':'短的','shot':'射击','should':'应该','shoulder':'肩膀',
    'shout':'喊','show':'展示','shower':'淋浴','shrink':'缩小',
    'shut':'关闭','shy':'害羞的','sick':'生病的','side':'边',
    'sidewalk':'人行道','sigh':'叹气','sight':'视觉','sign':'标志',
    'signal':'信号','signature':'签名','silence':'沉默','silent':'沉默的',
    'silk':'丝绸','silly':'傻的','silver':'银','similar':'相似的',
    'simple':'简单的','simply':'简单地','since':'自从','sincere':'真诚的',
    'sing':'唱歌','singer':'歌手','single':'单一的','sink':'下沉',
    'sir':'先生','sister':'姐妹','sit':'坐','site':'地点',
    'situation':'情况','six':'六','size':'尺寸','skate':'滑冰',
    'ski':'滑雪','skill':'技能','skin':'皮肤','skirt':'裙子',
    'sky':'天空','slap':'拍','slave':'奴隶','sleep':'睡觉',
    'slice':'片','slide':'滑动','slight':'轻微的','slim':'苗条的',
    'slip':'滑','slope':'斜坡','slow':'慢的','small':'小的',
    'smart':'聪明的','smell':'闻','smile':'微笑','smoke':'烟',
    'smooth':'光滑的','snake':'蛇','snow':'雪','so':'所以',
    'soap':'肥皂','soccer':'足球','social':'社会的','society':'社会',
    'sock':'袜子','soda':'苏打','sofa':'沙发','soft':'软的',
    'software':'软件','soil':'土壤','soldier':'士兵','solid':'固体的',
    'solution':'解决方案','solve':'解决','some':'一些','somebody':'某人',
    'someone':'某人','something':'某事','sometimes':'有时','somewhere':'某处',
    'son':'儿子','song':'歌曲','soon':'很快','sore':'疼痛的',
    'sorry':'抱歉的','sort':'种类','soul':'灵魂','sound':'声音',
    'soup':'汤','sour':'酸的','source':'来源','south':'南',
    'southern':'南方的','space':'空间','spare':'空闲的','speak':'说',
    'special':'特别的','specialist':'专家','specific':'具体的',
    'speech':'演讲','speed':'速度','spell':'拼写','spend':'花费',
    'spider':'蜘蛛','spirit':'精神','spiritual':'精神的','spit':'吐',
    'splash':'溅','split':'分开','spoil':'破坏','spoon':'勺子',
    'sport':'运动','spot':'斑点','spread':'传播','spring':'春天',
    'square':'广场','stable':'稳定的','stadium':'体育场','staff':'员工',
    'stage':'舞台','stair':'楼梯','stamp':'邮票','stand':'站',
    'standard':'标准','star':'星星','stare':'凝视','start':'开始',
    'state':'状态','station':'车站','stay':'停留','steady':'稳定的',
    'steal':'偷','steam':'蒸汽','steel':'钢','steep':'陡峭的',
    'step':'步骤','stick':'棍子','sticky':'粘的','stiff':'僵硬的',
    'still':'仍然','stir':'搅拌','stitch':'缝','stock':'库存',
    'stocking':'长袜','stomach':'胃','stone':'石头','stop':'停止',
    'store':'商店','storm':'暴风雨','story':'故事','stove':'炉子',
    'straight':'直的','strange':'奇怪的','stranger':'陌生人',
    'strategy':'策略','straw':'稻草','strawberry':'草莓','stream':'小溪',
    'street':'街道','strength':'力量','strengthen':'加强','stress':'压力',
    'stretch':'伸展','strict':'严格的','strike':'罢工','string':'绳子',
    'strip':'条','stripe':'条纹','stroke':'中风','strong':'强壮的',
    'structure':'结构','struggle':'斗争','student':'学生','studio':'工作室',
    'study':'学习','stuff':'东西','stupid':'愚蠢的','style':'风格',
    'subject':'科目','submit':'提交','substance':'物质',
    'substitute':'替代品','subtract':'减去','suburb':'郊区','subway':'地铁',
    'succeed':'成功','success':'成功','successful':'成功的',
    'such':'这样的','suck':'吸','sudden':'突然的','suddenly':'突然',
    'suffer':'受苦','sufficient':'足够的','sugar':'糖','suggest':'建议',
    'suggestion':'建议','suit':'西装','suitable':'合适的',
    'suitcase':'手提箱','sum':'总和','summer':'夏天','sun':'太阳',
    'sunlight':'阳光','sunny':'阳光的','sunrise':'日出','sunset':'日落',
    'sunshine':'阳光','super':'超级的','superior':'上级的',
    'supermarket':'超市','supper':'晚餐','supply':'供应','support':'支持',
    'suppose':'假设','sure':'确定的','surf':'冲浪','surface':'表面',
    'surgeon':'外科医生','surgery':'手术','surprise':'惊讶',
    'surround':'包围','survey':'调查','survival':'生存','survive':'幸存',
    'suspect':'怀疑','suspend':'暂停','swallow':'吞咽','swan':'天鹅',
    'swap':'交换','swear':'发誓','sweat':'汗','sweater':'毛衣',
    'sweep':'扫','sweet':'甜的','swell':'膨胀','swift':'迅速的',
    'swim':'游泳','swing':'摇摆','switch':'开关','sword':'剑',
    'symbol':'符号','sympathy':'同情','symptom':'症状','system':'系统',
    'table':'桌子','tablet':'药片','tag':'标签','tail':'尾巴',
    'tailor':'裁缝','take':'拿','tale':'故事','talent':'才能',
    'talk':'谈话','tall':'高的','tank':'坦克','tap':'水龙头',
    'tape':'磁带','target':'目标','task':'任务','taste':'味道',
    'tax':'税','taxi':'出租车','tea':'茶','teach':'教','teacher':'老师',
    'team':'队伍','tear':'眼泪','technical':'技术的','technique':'技术',
    'technology':'技术','teenager':'青少年','telegram':'电报',
    'telephone':'电话','telescope':'望远镜','television':'电视',
    'tell':'告诉','temper':'脾气','temperature':'温度','temple':'寺庙',
    'temporary':'临时的','ten':'十','tend':'倾向于','tendency':'倾向',
    'tennis':'网球','tense':'紧张的','tension':'紧张','tent':'帐篷',
    'term':'术语','terrible':'可怕的','terrific':'极好的',
    'territory':'领土','terror':'恐怖','test':'测试','text':'文本',
    'than':'比','thank':'感谢','that':'那个','the':'这个',
    'theater':'剧院','theft':'盗窃','their':'他们的','them':'他们',
    'theme':'主题','themselves':'他们自己','then':'那时','theory':'理论',
    'there':'那里','therefore':'因此','these':'这些','they':'他们',
    'thick':'厚的','thief':'小偷','thin':'薄的','thing':'事情',
    'think':'想','third':'第三','thirsty':'渴的','thirteen':'十三',
    'thirty':'三十','this':'这个','thorough':'彻底的','though':'虽然',
    'thought':'想法','thousand':'千','thread':'线','threat':'威胁',
    'threaten':'威胁','three':'三','throat':'喉咙','through':'通过',
    'throughout':'贯穿','throw':'扔','thumb':'拇指','thunder':'雷',
    'thus':'因此','ticket':'票','tide':'潮汐','tidy':'整洁的',
    'tie':'领带','tiger':'老虎','tight':'紧的','till':'直到',
    'time':'时间','tin':'锡','tiny':'微小的','tip':'尖端',
    'tire':'轮胎','tired':'累的','title':'标题','to':'到',
    'toast':'烤面包','tobacco':'烟草','today':'今天','toe':'脚趾',
    'together':'一起','toilet':'厕所','tomato':'番茄','tomb':'坟墓',
    'tomorrow':'明天','ton':'吨','tone':'语调','tongue':'舌头',
    'tonight':'今晚','too':'也','tool':'工具','tooth':'牙齿',
    'top':'顶部','topic':'话题','torch':'手电筒','total':'总计',
    'totally':'完全','touch':'触摸','tough':'坚韧的','tour':'旅行',
    'tourism':'旅游','tourist':'游客','toward':'朝','towel':'毛巾',
    'tower':'塔','town':'城镇','toy':'玩具','trace':'痕迹',
    'track':'轨道','trade':'贸易','tradition':'传统',
    'traditional':'传统的','traffic':'交通','tragedy':'悲剧',
    'train':'火车','training':'训练','transfer':'转移','transform':'改变',
    'translate':'翻译','translation':'翻译','transport':'运输',
    'transportation':'交通','trap':'陷阱','travel':'旅行','tray':'托盘',
    'treasure':'宝藏','treat':'对待','treatment':'治疗','tree':'树',
    'tremble':'颤抖','tremendous':'巨大的','trial':'审判',
    'triangle':'三角形','trick':'诡计','trip':'旅行','triumph':'胜利',
    'troops':'军队','tropical':'热带的','trouble':'麻烦',
    'trousers':'裤子','truck':'卡车','true':'真的','truly':'真正地',
    'trumpet':'小号','trust':'信任','truth':'真相','try':'尝试',
    'tube':'管','turkey':'火鸡','turn':'转动','twelve':'十二',
    'twenty':'二十','twice':'两次','twin':'双胞胎','twist':'扭转',
    'two':'二','type':'类型','typewriter':'打字机','typhoon':'台风',
    'typical':'典型的','ugly':'丑陋的','umbrella':'雨伞',
    'unable':'不能的','uncle':'叔叔','under':'在...下','undergo':'经历',
    'underground':'地下的','underline':'下划线','understand':'理解',
    'understanding':'理解','unfortunately':'不幸地','unhappy':'不快乐的',
    'uniform':'制服','union':'联盟','unique':'独特的','unit':'单位',
    'unite':'团结','universe':'宇宙','university':'大学',
    'unknown':'未知的','unless':'除非','until':'直到',
    'unusual':'不寻常的','up':'向上','upload':'上传','upon':'在...上',
    'upper':'上面的','upset':'心烦的','upstairs':'楼上','urban':'城市的',
    'urge':'催促','urgent':'紧急的','us':'我们','use':'使用',
    'used':'习惯的','useful':'有用的','useless':'无用的','user':'用户',
    'usual':'通常的','usually':'通常','vacant':'空缺的',
    'vacation':'假期','valid':'有效的','valley':'山谷',
    'valuable':'有价值的','value':'价值','van':'面包车','vanish':'消失',
    'variety':'多样性','various':'各种各样的','vary':'变化',
    'vast':'广阔的','vegetable':'蔬菜','vehicle':'车辆','venture':'冒险',
    'verb':'动词','version':'版本','very':'非常','vest':'马甲',
    'victim':'受害者','victory':'胜利','video':'视频','view':'景色',
    'village':'村庄','violence':'暴力','violent':'暴力的',
    'violin':'小提琴','virtual':'虚拟的','virtue':'美德','virus':'病毒',
    'visa':'签证','visible':'可见的','vision':'视力','visit':'拜访',
    'visitor':'访客','vital':'至关重要的','vitamin':'维生素',
    'vivid':'生动的','vocabulary':'词汇','voice':'声音','volume':'音量',
    'volunteer':'志愿者','vote':'投票','voyage':'航行','wage':'工资',
    'waist':'腰','wait':'等待','waiter':'服务员','wake':'醒来',
    'walk':'走','wall':'墙','wallet':'钱包','wander':'漫游',
    'want':'想要','war':'战争','warm':'温暖的','warn':'警告',
    'warning':'警告','wash':'洗','waste':'浪费','watch':'观看',
    'water':'水','waterfall':'瀑布','wave':'波浪','way':'方式',
    'we':'我们','weak':'弱的','weakness':'弱点','wealth':'财富',
    'wealthy':'富裕的','weapon':'武器','wear':'穿','weather':'天气',
    'weave':'编织','web':'网络','website':'网站','wedding':'婚礼',
    'weed':'杂草','week':'周','weekday':'工作日','weekend':'周末',
    'weekly':'每周的','weep':'哭泣','weigh':'称重','weight':'重量',
    'welcome':'欢迎','welfare':'福利','well':'好','west':'西',
    'western':'西方的','wet':'湿的','whale':'鲸鱼','what':'什么',
    'wheat':'小麦','wheel':'轮子','when':'当','where':'哪里',
    'whereas':'然而','whether':'是否','which':'哪个','while':'当...时',
    'whisper':'低语','whistle':'口哨','white':'白色','who':'谁',
    'whole':'整个的','whom':'谁','whose':'谁的','why':'为什么',
    'wide':'宽的','widely':'广泛地','wife':'妻子','wild':'野生的',
    'wildlife':'野生动物','will':'将','willing':'愿意的','win':'赢',
    'wind':'风','window':'窗户','wine':'酒','wing':'翅膀',
    'winner':'获胜者','winter':'冬天','wipe':'擦','wire':'电线',
    'wise':'明智的','wish':'希望','with':'和','withdraw':'撤回',
    'within':'在...内','without':'没有','witness':'目击者',
    'wolf':'狼','woman':'女人','wonder':'想知道',
    'wonderful':'精彩的','wood':'木头','wooden':'木制的','wool':'羊毛',
    'word':'词','work':'工作','worker':'工人','world':'世界',
    'worm':'虫子','worried':'担心的','worry':'担心','worse':'更坏的',
    'worship':'崇拜','worst':'最坏的','worth':'值得的','would':'会',
    'wound':'伤口','wrap':'包裹','wrist':'手腕','write':'写',
    'writer':'作家','writing':'写作','wrong':'错误的','yard':'院子',
    'year':'年','yellow':'黄色','yes':'是','yesterday':'昨天',
    'yet':'还','you':'你','young':'年轻的','your':'你的',
    'youth':'青春','zero':'零','zip':'拉链','zone':'区域','zoo':'动物园',
}

def is_english(text):
    if not text: return True
    return len(re.findall(r'[a-zA-Z]', text)) / max(len(text), 1) > 0.5

def translate_word_by_word(text):
    """Translate by looking up each word in the dictionary."""
    text = text.strip()
    # Direct lookup
    if text.lower() in D:
        return D[text.lower()]

    # Handle comma-separated meanings
    if ',' in text:
        parts = [p.strip() for p in text.split(',')]
        tr_parts = []
        for part in parts:
            t = translate_word_by_word(part)
            if t:
                tr_parts.append(t)
            else:
                tr_parts.append(part)
        result = '、'.join(tr_parts)
        if any('\u4e00' <= c <= '\u9fff' for c in result):
            return result

    # Word-by-word translation
    words = text.lower().replace('(', '').replace(')', '').split()
    translations = []
    found = 0
    for w in words:
        w_clean = w.strip('.,;:!?"\'')
        if w_clean in D:
            translations.append(D[w_clean])
            found += 1
        elif w_clean.rstrip('s') in D:
            translations.append(D[w_clean.rstrip('s')])
            found += 1
        elif w_clean.rstrip('ing') in D:
            translations.append(D[w_clean.rstrip('ing')])
            found += 1
        elif w_clean.rstrip('ed') in D:
            translations.append(D[w_clean.rstrip('ed')])
            found += 1
        elif w_clean.rstrip('ly') in D:
            translations.append(D[w_clean.rstrip('ly')])
            found += 1
        else:
            translations.append(w)

    if found > 0 and found >= len(words) * 0.5:
        return ''.join(translations)

    return None

def gen_example(jp, zh, cat):
    jp_c = jp.split('/')[0].strip()
    if '動詞' in cat or cat == '动词':
        return f'{jp_c}のは楽しいです。', f'{zh}是一件有趣的事。'
    elif '形容詞' in cat or cat == '形容词':
        return f'{jp_c}ですね。', f'真是{zh}呢。'
    elif '副詞' in cat or cat == '副词':
        return f'{jp_c}行きます。', f'{zh}去。'
    else:
        return f'{jp_c}は便利です。', f'{zh}很方便。'

# Load existing cache (API translations)
cache = {}
if os.path.exists('translation_cache.json'):
    with open('translation_cache.json', 'r', encoding='utf-8') as f:
        cache = json.load(f)
    print(f'API cache: {len(cache)} entries', flush=True)

with open(INPUT, 'r', encoding='utf-8') as f:
    content = f.read()

pat = r'\{ japanese: "(.*?)", hiragana: "(.*?)", romaji: "(.*?)", meaning_en: "(.*?)", meaning_zh: "(.*?)", jlpt_level: "(.*?)", category: "(.*?)", example_sentence: "(.*?)", example_translation: "(.*?)", is_premium: (\d+) \}'
matches = list(re.finditer(pat, content))
print(f'Total: {len(matches)}', flush=True)

new_lines = []
last_end = 0
api_tr = 0
dict_tr = 0
still_en = 0
ex_fixed = 0

for m in matches:
    new_lines.append(content[last_end:m.start()])
    last_end = m.end()

    jp, hiragana, romaji = m.group(1), m.group(2), m.group(3)
    en, zh = m.group(4), m.group(5)
    level, cat = m.group(6), m.group(7)
    ex_jp, ex_zh = m.group(8), m.group(9)
    prem = m.group(10)

    if is_english(zh):
        # Try API cache first
        if en in cache:
            zh = cache[en]
            api_tr += 1
        else:
            # Try dictionary
            tr = translate_word_by_word(en)
            if tr:
                zh = tr
                dict_tr += 1
            else:
                still_en += 1

    if is_english(ex_jp) or is_english(ex_zh):
        ex_jp, ex_zh = gen_example(jp, zh, cat)
        ex_fixed += 1

    new_lines.append(f'{{ japanese: "{jp}", hiragana: "{hiragana}", romaji: "{romaji}", meaning_en: "{en}", meaning_zh: "{zh}", jlpt_level: "{level}", category: "{cat}", example_sentence: "{ex_jp}", example_translation: "{ex_zh}", is_premium: {prem} }}')

new_lines.append(content[last_end:])

with open(INPUT, 'w', encoding='utf-8') as f:
    f.write(''.join(new_lines))

print(f'\nDONE!', flush=True)
print(f'API translations: {api_tr}', flush=True)
print(f'Dict translations: {dict_tr}', flush=True)
print(f'Still English: {still_en}', flush=True)
print(f'Examples fixed: {ex_fixed}', flush=True)
print(f'Total Chinese: {api_tr + dict_tr + (len(matches) - api_tr - dict_tr - still_en)}', flush=True)
